version: "3.7"
services:
  db:
    image: postgres:latest
    restart: on-failure
    env_file:
      - db.env
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - database
  pki:
    build:
      context: ./primekey
      dockerfile: Dockerfile
    restart: on-failure
    hostname: myca
    volumes:
      - pki-data:/mnt/persistent
    depends_on:
      - db
    env_file:
      - pki.env
    ports:
      - "443:8443"
      - "80:8080"
    networks:
      - web-facing
      - database
volumes:
  pki-data:
  db-data:
networks:
  database:
    internal: true
  web-facing:
