version: "3.7"
services:
#  db:
#    image: postgres:latest
#    restart: on-failure
#    env_file:
#      - db.env
#    volumes:
#      - db-data:/var/lib/postgresql/data
#    expose:
#      - "5432"
#    networks:
#      - database
  pki:
    build:
      context: ./primekey
      dockerfile: Dockerfile
    restart: on-failure
    hostname: localhost
    volumes:
      - ./db:/mnt/persistent
      - D:\Developpement\archi\lyra-keystore\ejbca-docker-build\ejbca_src\modules\dist\ejbca-ws-ejb.jar:/opt/primekey/ejbca/dist/ejbca.ear/ejbca-ws-ejb.jar
#    depends_on:
#      - db
    env_file:
      - pki.env
    ports:
      - "443:8443"
      - "80:8080"
    networks:
      - web-facing
      - database
networks:
  database:
    internal: true
  web-facing:
