FROM postgres:latest
#COPY sql_scripts/init.sql /docker-entrypoint-initdb.d/
#COPY sql_scripts/create-tables-ejbca-postgres.sql /docker-entrypoint-initdb.d/
#COPY sql_scripts/init-user-db.sh /docker-entrypoint-initdb.d/
#EXPOSE "5432"